### ISSUE TITLE
Possibility to assign Guest Users via CRP-Admin section

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO#1105] opened 2017-08-03 15:27 UTC
Currently, the guest users can be created directly in the database. it would be great if CRP-Admins could assign this kind of privileges by themselves.

**Technical Tasks needed:**
- [x]  Test guest user in Marlo dev-System Admin
- [ ]  Email when roles is assigned
- [ ]  Welcome Email
- [ ]  Test CGIAR and No-CGIAR user.
- [ ]  Work on the feedback received
- [ ]  Release it into production

**Comment by AndresFVR** [comment] 2017-10-17 19:01
Error message is wrong: https://www.screencast.com/t/G1artKAOuqP5

When a CRP/Center is selected and then is removed, i can not select it again: https://www.screencast.com/t/qenyMZ1a1Hw

Adding a No-CGIAR user with a duplicated user name, the following message is throw, maybe should say what is the error: https://www.screencast.com/t/ErjOaz6z

Welcome message display P&R instead of MARLO, adding a new Wheat guest user: https://www.screencast.com/t/ktEaoPASfYAv

**Comment by AndresFVR** [comment] 2017-10-17 19:15
Can not add a CGIAR user: https://www.screencast.com/t/cbfYcyt9s3

**Comment by jurodca** [comment] 2017-10-31 16:25
Fixed with commit https://github.com/CCAFS/MARLO/commit/b1f3b1f8ed36c2bd1c7e515be62883192890af41
the following issues (Error message should be improved to give more information to the user and what is the error or what left to complete the form,Adding a No-CGIAR user with a duplicated user name, the following message is throw, maybe should say what is the error,When a CRP/Center is selected and then is removed, i can not select it again).

This issue can't reproduce in any environment (Welcome message display P&R instead of MARLO, adding a new Wheat guest user, the only mail that the functionalluty sends is about Guest User or if the user is new, sends New User mail).

**Comment by htobon** [comment] 2017-10-31 16:29
@jurodca  Not sure I understood these latests comments. Can you please elaborate?

**Comment by htobon** [comment] 2017-10-31 16:52
Hi all, after testing in detail, here are my comments:
- [ ] If the user is Non-CGIAR, we should not ask for username. (Usernames are only being used for the active directory library that we are using in MARLO). all our users should login using their emails.
- [ ] If the user is Non-CGIAR, the system should create a random password and send it to the person via email.
- [ ] Although I filled a specific password in the field, the password sent in the email was different.
- [ ] The second emails informing about the roles (CIAT-Admin and FTA Guest) were never sent.

**Comment by htobon** [comment] 2017-11-03 21:30
- [ ] Admin roles are not being assigned for existing users
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e404382eb45a1cc11d5fe864bfe1f47256dc0d6959c097fd25dffaf8fe6cb552.png)

- [ ] I was not able to remove an Admin role.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-e0808dc2b6ed9be5cd9b08a97bdfa58e42e80bbd6124124f3baea29dd18362cb.png)

- [ ] Password must be required when user is marked with a non-cgiar account
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d306de13d426e3b8a99b6504dcb8c68d62b091a56180331c9e9ce4c31069bf87.png)

- [ ] It seems the save button is not working.
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7577f7a116633eca85734c92c885693bdb81aed60d278861610b683b0e915e75.png)

**Comment by sebas932** [comment] 2017-11-09 16:58
[ ]-  I got the following error when i tried to assign my user as CRP Admin of all CRPs listed

>java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	java.util.ArrayList.rangeCheck(ArrayList.java:653)
	java.util.ArrayList.get(ArrayList.java:429)
	org.cgiar.ccafs.marlo.action.json.global.ManageUsersAction.checkNewCRPs(ManageUsersAction.java:442)
	org.cgiar.ccafs.marlo.action.json.global.ManageUsersAction.manageUserWithPrivileges(ManageUsersAction.java:702)

**Comment by htobon** [comment] 2018-01-15 21:17
Let's finish this module in the next sprint. 
The idea then would be to take out the CRP-Admin part and focus this module on Guest Users only.

I have already talked this task with @jurodca and he agreed in working on it during the sprint v4.2.3.

**Closed** 2021-08-10 19:55 UTC
Labels: Type - Enhancement
