### ISSUE TITLE
BUG: budgets_view and user_permissions view do not appear to be working in production

### ISSUE THREAD

**Issue by Grant-Lay** [CCAFS/MARLO#1228] opened 2018-01-11 07:05 UTC
After having some problems with my local environment I have logged into production to check if the views budgets_view and user_permissions view are working correctly.  They appear to be broken in the production environment also.

Error messages display:  

- [x]  View 'marloDB.user_permissions' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
![user_permissions](https://user-images.githubusercontent.com/2264925/34812463-3f47449a-f6d8-11e7-9e2b-31f19fe99275.png)

- [x]  View 'marloDB.budgets_view' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
![budget_view](https://user-images.githubusercontent.com/2264925/34812486-54fb12d0-f6d8-11e7-86fa-2ba441c9fabe.png)

**Comment by cgarcia9106** [comment] 2018-01-11 12:36
user_permissions view change to a sp , call user_permissions (user_id); select * from user_permission;

**Comment by htobon** [comment] 2018-01-11 20:39
@Grant-Lay, thanks for spotting this.

@cgarcia9106 and @AndresFVR checked them and confirmed they are not used any more. Thus, they will be deleted in a database migration.

**Comment by AndresFVR** [comment] 2018-01-11 20:55
Hi @Grant-Lay we have deleted both views in a migration, please refer to the following commit [0773335](https://github.com/CCAFS/MARLO/commit/0773335351c11a26b19fad23d3a3eec8672700d1)

**Comment by htobon** [comment] 2018-01-17 20:53
Closing this issue as this seems to be solved now.

**Closed by htobon** 2018-01-17 20:53 UTC
Labels: Priority - Low, Type - Bug
